apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}
type: Opaque
data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.eventBridgeName }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.eventBridgeName }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bundle.fullname" . }}
        component: {{ template "bundle.fullname" . }}-{{ .Values.eventBridgeName }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: {{ .Values.eventBridgeName }}
        image: "jcawley5/fg-event-gw"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        envFrom:
          - secretRef:
              name: {{ template "bundle.fullname" . }}
              optional: false
        args:
          - --app-name={{ .Values.application_name }}
          - --password=$(password)
          - --username=$(username)
          - --event-publish-url=http://event-publish-service.kyma-system.svc.cluster.local:8080/v1/events
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.eventBridgeName }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.eventBridgeName }}
spec:
  selector:
    component: {{ template "bundle.fullname" . }}-{{ .Values.eventBridgeName }}
  ports:
    - port: 8080
      name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.eventBridgeName }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.eventBridgeName }}
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - {{ template "eb_server" . }}
  http:
  - match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: {{ template "bundle.fullname" . }}-{{ .Values.eventBridgeName }}
        port:
          number: 8080
    websocketUpgrade: true