apiVersion: v1
kind: Service
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
spec:
  ports:
  - name: http
    port: 10000
  selector:
    app: {{ template "bundle.fullname" . }}
